### ISSUE TITLE
synapseclient.core.exceptions.SynapseHTTPError: 403 Client Error:  insufficient_scope. Request lacks scope(s) required by this service: modify

### ISSUE THREAD

**Issue by FengheTan9** [Sage-Bionetworks/synapsePythonClient#1075]
Traceback (most recent call last):
  File "E:\project\segment\3d\chanllenge\result\submit_evaluation.py", line 114, in <module>
    PARTICIPANT_FILE = SYN.store(File(ARGS.directory,
  File "D:\work\pythonfamily\envs\cv\lib\contextlib.py", line 75, in inner
    return func(*args, **kwds)
  File "D:\work\pythonfamily\envs\cv\lib\site-packages\synapseclient\client.py", line 1674, in store
    fileHandle = upload_file_handle(
  File "D:\work\pythonfamily\envs\cv\lib\contextlib.py", line 75, in inner
    return func(*args, **kwds)
  File "D:\work\pythonfamily\envs\cv\lib\site-packages\synapseclient\core\upload\upload_functions.py", line 146, in upload_file_handle
    return upload_synapse_s3(
  File "D:\work\pythonfamily\envs\cv\lib\site-packages\synapseclient\core\upload\upload_functions.py", line 283, in upload_synapse_s3
    file_handle_id = multipart_upload_file(
  File "D:\work\pythonfamily\envs\cv\lib\contextlib.py", line 75, in inner
    return func(*args, **kwds)
  File "D:\work\pythonfamily\envs\cv\lib\site-packages\synapseclient\core\upload\multipart_upload.py", line 514, in multipart_upload_file
    return _multipart_upload(
  File "D:\work\pythonfamily\envs\cv\lib\site-packages\synapseclient\core\upload\multipart_upload.py", line 709, in _multipart_upload
    upload_status_response = UploadAttempt(
  File "D:\work\pythonfamily\envs\cv\lib\site-packages\synapseclient\core\upload\multipart_upload.py", line 397, in __call__
    upload_status_response = self._create_synapse_upload()
  File "D:\work\pythonfamily\envs\cv\lib\site-packages\synapseclient\core\upload\multipart_upload.py", line 148, in _create_synapse_upload
    return self._syn.restPOST(
  File "D:\work\pythonfamily\envs\cv\lib\contextlib.py", line 75, in inner
    return func(*args, **kwds)
  File "D:\work\pythonfamily\envs\cv\lib\site-packages\synapseclient\client.py", line 5907, in restPOST
    response = self._rest_call(
  File "D:\work\pythonfamily\envs\cv\lib\site-packages\synapseclient\client.py", line 5849, in _rest_call
    self._handle_synapse_http_error(response)
  File "D:\work\pythonfamily\envs\cv\lib\site-packages\synapseclient\client.py", line 5786, in _handle_synapse_http_error
    exceptions._raise_for_status(response, verbose=self.debug)
  File "D:\work\pythonfamily\envs\cv\lib\site-packages\synapseclient\core\exceptions.py", line 159, in _raise_for_status
    raise SynapseHTTPError(message, response=response)
synapseclient.core.exceptions.SynapseHTTPError: 403 Client Error: 
insufficient_scope. Request lacks scope(s) required by this service: modify

**Comment by BryanFauble** [comment]
Hi @FengheTan9 ,

You'll need to create a new personal access token with:

1. view
2. download
3. modify

permissions in order to fully use this python package.[ Further documentation on authentication can be found here.](https://python-docs.synapse.org/tutorials/authentication/) Please re-open if this does not resolve your problem.
