### ISSUE TITLE
KeyError: 'X-Amz-Date'

### ISSUE THREAD

**Issue by jaewon-cho** [Sage-Bionetworks/synapsePythonClient#1141]
Hello Synapse team
I was trying to download a data with synapse

my code
synapse get syn24245376

after authorization with my token, I received such error

[ERROR] Error occurred while running <coroutine object download_file_entity at 0x7faf74aa4cc0> in a sync context.
Traceback (most recent call last):
  File "/PHShome/jc1062/miniconda3/envs/compass_env/lib/python3.8/site-packages/synapseclient/core/async_utils.py", line 93, in wrap_async_to_sync
    return asyncio.run(coroutine)
  File "/PHShome/jc1062/miniconda3/envs/compass_env/lib/python3.8/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/PHShome/jc1062/miniconda3/envs/compass_env/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "/PHShome/jc1062/miniconda3/envs/compass_env/lib/python3.8/site-packages/synapseclient/core/download/download_functions.py", line 172, in download_file_entity
    download_path = await download_by_file_handle(
  File "/PHShome/jc1062/miniconda3/envs/compass_env/lib/python3.8/site-packages/synapseclient/core/download/download_functions.py", line 515, in download_by_file_handle
    downloaded_path = await loop.run_in_executor(
  File "/PHShome/jc1062/miniconda3/envs/compass_env/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/PHShome/jc1062/miniconda3/envs/compass_env/lib/python3.8/site-packages/synapseclient/core/download/download_functions.py", line 517, in <lambda>
    lambda: download_from_url(
  File "/PHShome/jc1062/miniconda3/envs/compass_env/lib/python3.8/site-packages/synapseclient/core/download/download_functions.py", line 751, in download_from_url
    ) + PresignedUrlProvider._TIME_BUFFER >= _pre_signed_url_expiration_time(
  File "/PHShome/jc1062/miniconda3/envs/compass_env/lib/python3.8/site-packages/synapseclient/core/download/download_async.py", line 225, in _pre_signed_url_expiration_time
    time_made = parsed_query["X-Amz-Date"][0]
KeyError: 'X-Amz-Date'

Can anyone help me?

**Comment by BWMac** [comment]
Hi @jaewon-cho this is a known issue with version `v4.5` of `synapseclient` which will be addressed in a new release soon. In the meantime, the best way to proceed is to use `v4.4` instead.

**Comment by thomasyu888** [comment]
Hi @jaewon-cho ,

Please take a look at this: https://github.com/Sage-Bionetworks/synapsePythonClient/issues/1138#issuecomment-2379939677

I will have to take a closer look at your file, but if it is located in a Google bucket, please downgrade the python client version for now as we are working on minting a release as soon as possible.

**Comment by thomasyu888** [comment]
@jaewon-cho Closing this now as v4.6.0 has the fix!
