### ISSUE TITLE
synapseutils.sync.syncFromSynapse throws error when syncing a Table object

### ISSUE THREAD

**Issue by scottkd** [Sage-Bionetworks/synapsePythonClient#469]
There appears to be a bug in synapseutils.sync.syncFromSynapse. I am attempting to sync the 'Wondrous Research Example' (syn1901847) to my local filesystem. The syncFromSynapse function is throwing this error:
```
Traceback (most recent call last):
  ...
  File "import_synapse.py", line 55, in import_synapse_files
    synapseutils.sync.syncFromSynapse(synapse_client, syn_id, output_path)
  File "~/anaconda/envs/py27/lib/python2.7/site-packages/synapseutils/sync.py", line 82, in syncFromSynapse
    syncFromSynapse(syn, result['entity.id'], new_path, ifcollision, allFiles)
  File "~/anaconda/envs/py27/lib/python2.7/site-packages/synapseutils/sync.py", line 90, in syncFromSynapse
    generateManifest(syn, allFiles, filename)
  File "~/anaconda/envs/py27/lib/python2.7/site-packages/synapseutils/sync.py", line 107, in generateManifest
    row = {'parent': entity['parentId'], 'path': entity.path, 'name': entity.name,
  File "~/anaconda/envs/py27/lib/python2.7/site-packages/synapseclient/entity.py", line 362, in __getattr__
    raise AttributeError(key)
AttributeError: path
```

I added a print statement to the entity to determine which resource was causing this error, and this appears to be the culprit:
```
Schema: Synapse Table Demo (syn3079449)
  columns_to_store=None
properties:
  accessControlList=/repo/v1/entity/syn3079449/acl
  annotations=/repo/v1/entity/syn3079449/annotations
  columnIds=[u'36450', u'36451', u'36452', u'36453']
  concreteType=org.sagebionetworks.repo.model.table.TableEntity
  createdBy=273979
  createdOn=2015-01-09T20:49:19.646Z
  entityType=org.sagebionetworks.repo.model.table.TableEntity
  etag=b6d017c7-18a8-47e7-8bd7-497bf8b1a512
  id=syn3079449
  modifiedBy=273979
  modifiedOn=2015-01-09T20:49:19.646Z
  name=Synapse Table Demo
  parentId=syn1901847
  uri=/repo/v1/entity/syn3079449
  versionLabel=1
  versionNumber=1
  versionUrl=/repo/v1/entity/syn3079449/version/1
  versions=/repo/v1/entity/syn3079449/version
annotations:
```

**Comment by zimingd** [comment]
Thank you for the report. This should now be fixed in #476
JIRA issue: https://sagebionetworks.jira.com/browse/SYNPY-558
