### ISSUE TITLE
from backports import csv

### ISSUE THREAD

**Issue by fizwit** [Sage-Bionetworks/synapsePythonClient#504]
csv is available natively with Python 2 and 3.
Can you change: from backports import csv
too:  import csv

```Python 3.6.4 (default, Jan 11 2018, 12:42:15)
[GCC 5.4.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import synapseclient
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/app/easybuild/software/Python/3.6.4-foss-2016b-fh1/lib/python3.6/site-packages/synapseclient-1.7.3-py3.6.egg/synapseclient/__init__.py", line 308, in <module>
    from .client import Synapse, login
  File "/app/easybuild/software/Python/3.6.4-foss-2016b-fh1/lib/python3.6/site-packages/synapseclient-1.7.3-py3.6.egg/synapseclient/client.py", line 86, in <module>
    from .table import Schema, Column, TableQueryResult, CsvFileTable
  File "/app/easybuild/software/Python/3.6.4-foss-2016b-fh1/lib/python3.6/site-packages/synapseclient-1.7.3-py3.6.egg/synapseclient/table.py", line 276, in <module>
    from backports import csv
ImportError: cannot import name 'csv'
>>> import csv
>>> from backports import csv
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: cannot import name 'csv'
>>>
```

```Python 2.7.14 (default, Nov  8 2017, 15:22:40)
[GCC 5.4.0] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> from backpots import csv
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: No module named backpots
>>> import csv
>>>
```

**Comment by zerodel** [comment]
meet the same error . did your change works correctly ? 
my situation :
invoke the synapse in the command line ,it returns : 
`
Traceback (most recent call last):
  File "/Users/zerodel/anaconda3/bin/synapse", line 4, in <module>
    import synapseclient.__main__
  File "/Users/zerodel/anaconda3/lib/python3.6/site-packages/synapseclient/__init__.py", line 308, in <module>
    from .client import Synapse, login
  File "/Users/zerodel/anaconda3/lib/python3.6/site-packages/synapseclient/client.py", line 85, in <module>
    from .table import Schema, Column, TableQueryResult, CsvFileTable
  File "/Users/zerodel/anaconda3/lib/python3.6/site-packages/synapseclient/table.py", line 276, in <module>
    from backports import csv
ImportError: cannot import name 'csv'

`

**Comment by zimingd** [comment]
The required package is "backports.csv" https://pypi.python.org/pypi/backports.csv
`pip install backports.csv`

It should have been automatically installed along with synapseclient because it is listed as a dependency but if for some odd reason it did not, installing it manually should work.

**Comment by zimingd** [comment]
@fizwit
We can't remove this dependency because we need a CSV module that supports Unicode in Python 2

**Comment by buptbf** [comment]
I meet the same error, when I run  :
pip install backports.csv
Again run my command before, it works.
Thank you@zimingd
