### ISSUE TITLE
When downloading using Python 2.7 backport csv writer gives an UnicodeEncodeError

### ISSUE THREAD

**Issue by npklein** [Sage-Bionetworks/synapsePythonClient#530]
When trying to download syn3163039 with `files = synapseutils.syncFromSynapse(syn, "syn3163039", path='syn3163039/")` I get the below error. It works correctly when using Python 3. 

Traceback (most recent call last):
  File "download_data.py", line 12, in <module>
    files = synapseutils.syncFromSynapse(syn, "syn3163039", path='syn3163039/")
  File "/apps/software/Python/2.7.11-foss-2015b/lib/python2.7/site-packages/synapseutils/sync.py", line 85, in syncFromSynapse
    syncFromSynapse(syn, result['id'], new_path, ifcollision, allFiles, followLink=followLink)
  File "/apps/software/Python/2.7.11-foss-2015b/lib/python2.7/site-packages/synapseutils/sync.py", line 85, in syncFromSynapse
    syncFromSynapse(syn, result['id'], new_path, ifcollision, allFiles, followLink=followLink)
  File "/apps/software/Python/2.7.11-foss-2015b/lib/python2.7/site-packages/synapseutils/sync.py", line 85, in syncFromSynapse
    syncFromSynapse(syn, result['id'], new_path, ifcollision, allFiles, followLink=followLink)
  File "/apps/software/Python/2.7.11-foss-2015b/lib/python2.7/site-packages/synapseutils/sync.py", line 105, in syncFromSynapse
    generateManifest(syn, allFiles, filename)
  File "/apps/software/Python/2.7.11-foss-2015b/lib/python2.7/site-packages/synapseutils/sync.py", line 145, in generateManifest
    csvWriter.writerow(row)
  File "/apps/software/Python/2.7.11-foss-2015b/lib/python2.7/site-packages/backports/csv.py", line 685, in writerow
    return self.writer.writerow(self._dict_to_list(rowdict))
  File "/apps/software/Python/2.7.11-foss-2015b/lib/python2.7/site-packages/backports/csv.py", line 204, in writerow
    return self.fileobj.write(line)

**Comment by zimingd** [comment]
I'll try to reproduce this.
Could you also provide information about which operating system you are using and the error message of the UnicodeEncodeError?

**Comment by zimingd** [comment]
Nevermind, I was able reproduce this using just backports.csv. Looking into a fix now.

**Comment by zimingd** [comment]
Progress tracked in:
https://sagebionetworks.jira.com/browse/SYNPY-693

**Comment by zimingd** [comment]
Fixed in release 1.8.0
