### ISSUE TITLE
2.4.0 release doesn't generate easy_path file

### ISSUE THREAD

**Issue by najoshi** [Sage-Bionetworks/synapsePythonClient#872]
Installing on ubuntu from source, doesn't generate the easy_path file. Then errors out when trying to find the synapseclient package.

**Comment by thomasyu888** [comment]
Hi @najoshi , 

Could you provide more information / stack trace?

**Comment by najoshi** [comment]
Traceback (most recent call last):
  File "/software/synapseclient/2.4.0/lssc0-linux/bin/synapse", line 33, in <module>
    sys.exit(load_entry_point('synapseclient==2.4.0', 'console_scripts', 'synapse')())
  File "/software/synapseclient/2.4.0/lssc0-linux/bin/synapse", line 22, in importlib_load_entry_point
    for entry_point in distribution(dist_name).entry_points
  File "/software/anaconda3/4.9.2/lssc0-linux/lib/python3.9/importlib/metadata.py", line 524, in distribution
    return Distribution.from_name(distribution_name)
  File "/software/anaconda3/4.9.2/lssc0-linux/lib/python3.9/importlib/metadata.py", line 187, in from_name
    raise PackageNotFoundError(name)
importlib.metadata.PackageNotFoundError: synapseclient

**Comment by najoshi** [comment]
Once I added the easy-install.pth file, it worked just fine.

**Comment by najoshi** [comment]
or maybe it was the site.py file that I copied over from an older version

**Comment by thomasyu888** [comment]
Are you running `pip install synapseclient`？

**Comment by najoshi** [comment]
python setup.py install --prefix=<install dir>

**Comment by thomasyu888** [comment]
Closing this as this was tackled in later versions of the client.
