### ISSUE TITLE
login error

### ISSUE THREAD

**Issue by ptnaimelmm** [Sage-Bionetworks/synapsePythonClient#897]
# Bug Report

Got an error as follows when logining with syn.login.

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/scratch/users/mliu63@jhu.edu/synapsedl_env/lib/python3.10/site-packages/synapseclient/client.py", line 429, in login
    delete_stored_credentials(self.credentials.username)
  File "/scratch/users/mliu63@jhu.edu/synapsedl_env/lib/python3.10/site-packages/synapseclient/core/credentials/cred_data.py", line 190, in delete_stored_credentials
    creds = credential_cls.get_from_keyring(username)
  File "/scratch/users/mliu63@jhu.edu/synapsedl_env/lib/python3.10/site-packages/synapseclient/core/credentials/cred_data.py", line 35, in get_from_keyring
    secret = keyring.get_password(cls.get_keyring_service_name(), username)
  File "/scratch/users/mliu63@jhu.edu/synapsedl_env/lib/python3.10/site-packages/keyring/core.py", line 55, in get_password
    return get_keyring().get_password(service_name, username)
  File "/scratch/users/mliu63@jhu.edu/synapsedl_env/lib/python3.10/site-packages/keyring/backends/fail.py", line 25, in get_password
    raise NoKeyringError(msg)
keyring.errors.NoKeyringError: No recommended backend was available. Install a recommended 3rd party backend package; or, install the keyrings.alt package if you want to use the non-recommended backends. See https://pypi.org/project/keyring for details. 

Would you please give any suggestions? Thanks.

**Comment by thomasyu888** [comment]
Python 3.10 is now supported and this shouldn't be an issue.
